import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Full autogenerated sidebar (keeps generated-index pages alive for all sections).
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
  // Scoped sidebars used by the navbar tabs.
  etherCatSidebar: [
    {
      type: 'autogenerated',
      dirName: 'ethercat-basics',
    },
  ],
  hardwareSidebar: [
    {
      type: 'autogenerated',
      dirName: 'hardware',
    },
  ],
};

export default sidebars;
