import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The sidebar is fully autogenerated from the folder structure under `docs/`.
 *
 * To add a new page: drop a `.md`/`.mdx` file into the relevant section folder.
 * To add a new section: create a new folder with a `_category_.json` file.
 *
 * No edits to this file are required for either case.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
